module.exports = {
  positive: [
    "good", "great", "positive", "happy", "success", "beneficial", "excellent",
    "amazing", "awesome", "favorable", "fantastic", "joyful", "delightful", "splendid",
    "marvelous", "incredible", "wonderful", "optimistic", "loved", "cherished", "uplifting",
    "commendable", "admirable", "brilliant", "victorious", "inspired", "energized", "exciting",
    "impressive", "thrilling", "invigorating", "enjoyable", "pleasurable", "satisfying", "rewarding",
    "lovely", "radiant", "sunny", "heartening", "encouraging", "promising", "successful", "secure",
    "reliable", "trustworthy", "progressive", "advantageous", "fortunate", "prosperous", "thriving",
    "lively", "vibrant", "exhilarating", "breathtaking", "stunning", "innovative", "creative",
    "productive", "efficient", "effective", "improved", "enhanced", "remarkable", "amusing",
    "charming", "sweet", "elegant", "graceful", "peaceful", "calm", "serene", "tranquil", "harmonious",
    "friendly", "cordial", "affable", "benevolent", "kind", "considerate", "compassionate", "loving",
    "supportive", "reassuring", "cheerful", "vivacious", "spirited", "zestful", "dynamic", "energetic",
    "motivated", "enthusiastic", "passionate", "determined", "confident", "proud", "glorious",
    "celebratory", "exultant", "beaming", "jubilant",
  ],
  negative: [
    "bad", "poor", "negative", "sad", "failure", "harmful", "terrible", "awful", "horrible",
    "disappointing", "miserable", "gloomy", "depressed", "bleak", "tragic", "upsetting",
    "dismal", "dire", "worthless", "inferior", "unsatisfactory", "unworthy", "destructive",
    "adverse", "detrimental", "obnoxious", "repulsive", "revolting", "nasty", "horrid",
    "discouraging", "wretched", "deplorable", "abysmal", "rotten", "sorrowful", "somber",
    "distressing", "painful", "pathetic", "lamentable", "pitiful", "woeful", "regretful",
    "disheartening", "exasperating", "maddening", "frustrating", "mournful", "heartbroken",
    "depressing", "toxic", "venomous", "hostile", "bitter", "rancorous", "spiteful", "unkind",
    "malicious", "lethal", "dangerous", "vile", "obscene", "repugnant", "scandalous",
    "disgraceful", "shameful", "offensive", "detestable", "abominable", "horrendous", "foul",
    "corrupt", "unsavory", "grim", "forlorn", "despondent", "pessimistic", "unpromising",
    "alarming", "unsettling", "shocking", "unbearable", "dreadful", "monstrous", "appalling",
    "dejected", "hopeless", "insecure", "substandard", "mediocre", "flimsy", "enervating",
    "draining", "stressful", "burdensome", "harsh", "cold", "acerbic", "atrocious",
  ],
};
